- example/server_client/server_client.ipynb
- uniflow/client.py
- uniflow/constants.py
- uniflow/server.py
add uniflow server and client
- add uniflow server
- add uniflow client
- add uniflow server-client example
> add uniflow server and client

- uniflow/constants.py
- uniflow/flow/flow.py
- uniflow/flow/flow_text_plus_data_gen.py
- uniflow/op/pdf_qa_gen/data_output_text_op.py
- uniflow/op/self_instructed_op/data_output_si_op.py
- uniflow/op/self_instructed_op/preprocess_html_op.py
- uniflow/op/self_instructed_op/si_model_inf_op.py
- uniflow/op/utils.py
- Integrate logging into the different flows
- added logging for check_path_exists util
- format with black
> Refactor to use logging instead of print, format with black

- uniflow/flow/constants.py
- uniflow/op/self_instructed_op/data_output_si_op.py
- uniflow/op/self_instructed_op/si_model_inf_op.py
Move constructors to an __init__ method to avoid constructing for every node
> Refactor self_instruct_op with init

- example/qa_generation/data_generation.ipynb
- uniflow/config.py
- uniflow/op/qa_gen/preprocess_op.py
- uniflow/op/qa_gen/prompt_eng_op.py
- uniflow/op/self_instructed_op/si_model_inf_op.py
Add set and get functions to config.py file to allow end user to set a QA_FACTOR, which determines the factor by which the output QA are generated relative to the input QA
> Make output number for QA-> more QA configurable

- tests/flow/test_data_gen_flow.py
- tests/flow/test_flow.py
- tests/op/test_op.py
- update constants in test_data_gen_flow
- add constants and fix .run in test_flow
- update test_op to clear op name on tearDown
> Fix unittests

- README.md
- uniflow/op/self_instructed_op/si_model_inf_op.py
- correct self-instruct finetuning to self-instruct data generation;
- polish and generalize examples;
> Example and ReadME polish

- README.md
- example/qa_generation/data/raw_input/22.4_multivariable-calculus.html
- example/qa_generation/data_generation_text.ipynb
- example/self_instructed_ft/demo_self_instruct_ft.ipynb
- uniflow/flow/constants.py
- uniflow/flow/flow.py
- uniflow/flow/flow_data_gen_text.py
- uniflow/flow/flow_text_plus_data_gen.py
- uniflow/op/pdf_qa_gen/data_output_text_op.py
- uniflow/op/pdf_qa_gen/lmqg_op.py
- uniflow/op/pdf_qa_gen/preprocess_file_op.py
- uniflow/op/pdf_qa_gen/preprocess_text_op.py
- uniflow/op/self_instructed_op/preprocess_html_op.py
- uniflow/op/self_instructed_op/si_model_inf_op.py
- Add preprocess_file_op to handle .txt and .html files
- update lmqp_op to run a single paragraph at a time
- update data_generation_text.ipynb with 22.4_multivariable-calculus.html example
> Update DataGenTextFlow for HTML processing

- README.md
- example/qa_generation/README.md
- example/self_instructed_ft/README.md
- Update main README to link to README and example folders
- Add README for qa_generation example notebooks
- Add README for self_instructed_ft example notebook
> updated README with structure to add README in example folders

- example/qa_generation/text_plus_data_generation.ipynb
- uniflow/config.py
- uniflow/flow/flow.py
- uniflow/flow/flow_text_plus_data_gen.py
- added handling for duplicate "linear_op" in flow.py
- modify flow to use INPUT_FILE key, and update notebook example
> Update text_plus_data_gen to use INPUT_FILE in input_dict

- example/self_instructed_ft/demo_self_instruct_ft.ipynb
-  output results and add comments
> Polish self_instructed_ft example

- uniflow/model/model.py
Rewrite the error message to be "No Error" rather than "Failed to deserialize 0 examples".
> Clarify the error message

- README.md
- example/model/huggingface_model.ipynb
- example/model/openai_pdf_source_10k.ipynb
- Add comments
- Add benchmarking results
- Fix README installation
> Finish Hugginface Model Flow Example

- uniflow/flow/config.py
- uniflow/flow/transform/__init__.py
- uniflow/flow/transform/transform_azure_openai_flow.py
- uniflow/op/model/model_config.py
- uniflow/op/model/model_server.py
- refactor rater config
- add azure openai server
> refactor rater config and add azure openai server

- uniflow/flow/config.py
- uniflow/flow/server.py
- uniflow/op/extract/split/splitter_factory.py
- uniflow/op/model/model_config.py
- uniflow/op/model/model_server.py
- black entire uniflow
- fix bug for BedrockModelServer
- update huggingface configuration
> update huggingface configuration with other minor fix

- uniflow/flow/config.py
- uniflow/op/model/abs_llm_processor.py
- uniflow/op/model/model_config.py
- uniflow/op/model/model_server.py
TODO
- add notebook
Need two more notebook for HuggingFace to use 
- `TransformQAHuggingFaceConfig`: raw format
- `TransformQAHuggingFaceJsonFormatConfig`: format in json
> Add HuggingFace model instruction token for better IF performance.

- uniflow/flow/config.py
- reformat linter error caused by https://github.com/CambioML/uniflow/pull/105
> Fix black issue

- uniflow/flow/config.py
Fix `gpt4` to `gpt-4-1106-preview` to allow JSON
> Fix `gpt4` to `gpt-4-1106-preview` to allow JSON

- uniflow/op/model/model_config.py
- uniflow/op/model/model_server.py
Similar to https://github.com/CambioML/uniflow-llm-text-data-cleaning-cluster/pull/147, add ThreadPoolExecutor for  Azure OpenAI endpoint.
> Add ThreadPoolExecutor for Azure OpenAI endpoint

- uniflow/op/extract/load/html_op.py
> Unified HTML Extract 

- uniflow/op/model/model_server.py
- uniflow/op/model/neuron_utils.py
https://github.com/CambioML/uniflow-llm-text-data-cleaning-cluster/issues/179
> fix a bug on inf2.8x with batch_size= 1 or 2

- uniflow/op/extract/load/utils.py
- Update requests to mimic a browser request with header
> Update requests to mimic a browser request with header
