- uniflow/model/server.py
Fix batch inference. 
batch 8:
100%|██████████| 10/10 [00:35<00:00,  3.56s/it]
batch 4:
100%|██████████| 20/20 [01:01<00:00,  3.08s/it]
batch 2:
100%|██████████| 40/40 [01:11<00:00,  1.79s/it]
batch 1:
100%|██████████| 80/80 [01:12<00:00,  1.10it/s]
one caveat for my test is that I am using the exactly same length for each datapoint in a batch. If you are using different input size, it will slow down the batch inference due to padding.
> fix huggingface batch inference by explicitly specify batch inference batch size

- uniflow/op/model/model_server.py
fix model_server missing import packages, which should resolve issue #65
> fix model_server missing import packages

- .github/workflows/python-app.yml
- .pre-commit-config.yaml
- tests/flow/test_flow.py
- tests/op/test_op.py
- add isort, autoflake, and mypy to pre-commit
- add github action to check dependencies, lint with flake8, and run unittests
- Fix unittests
> Add pre-commit and github action checks

- example/rater/classification.ipynb
- example/rater/generated_answer.ipynb
- correct grammar errors
- add clear code descriptions
> polish autorater notebooks

- example/rater/bedrock_classification.ipynb
- uniflow/op/model/model_config.py
- uniflow/op/model/model_server.py
- Add BedrockModelServer in model_server.py
- Add BedrockModelConfig in model_config.py
- Add bedrock_classification.ipynb as an example
> feat: Add Bedrock Support

- .github/workflows/python-app.yml
- tests/test_node.py
- tests/test_viz.py
- remove line-length=127 arguments for black, isort, and flake8
- add --check and --check-only to black and isort commands
> remove line length and make black and isort check only and throw error

- uniflow/flow/rater/rater_flow.py
This is a quick and dirty fix that `JsonFormattedLLMRater` is only for OpenAI model to return json string and use load to load into json object. 
For other model, it must use LLMRater such as Huggingface model, it further support `json_object` by manually parse the response into json format while not relying on the model.
> Fix non openai model to not use JsonFormattedLLMRater

- uniflow/flow/rater/rater_flow.py
- uniflow/op/model/llm_processor.py
- revert https://github.com/CambioML/uniflow/pull/116
- add a check regarding whether return object is already in json or not.
> Fix HuggingFace rater json object which already return the response in json dict, so no need to json.loads

- example/llm/sagemaker_deploy.ipynb
- example/llm/sagemaker_deploy_mistral.ipynb
- uniflow/flow/config.py
- uniflow/op/model/model_config.py
- uniflow/op/model/model_server.py
- uniflow/op/prompt.py
- Add sagemaker_deploy.ipynb and sagemaker_deploy_mistral to deploy a model from Huggingface Hub on SageMaker Endpoint
- Add SageMakerModelConfig in model_config.py
- Add SageMakerModelServer in model_server.py
> feat: Add SageMaker Endpoint Sample and SageMaker Model Server

- tests/op/test_op.py
- uniflow/op/op.py
- uniflow/op/utils.py
This is a design mistake to include `Ops` name. Instead, we only need to keep unique node name to show the computational graph through graphviz.
> Remove Ops name check

- uniflow/op/model/model_server.py
Fix bug introduce by https://github.com/CambioML/uniflow/pull/136/files. In order to check whether key is in a Pydantic BaseModel, we need to use 
```
"few_shot_prompt" in prompt_template.model_fields
```
instead of 
```
"few_shot_prompt" in prompt_template
```
"few_shot_prompt" in prompt_template will always return `false`.
@SayaZhang
> Fix check key in Pydantic BaseModel class bug

- example/extract/extract_html.ipynb
- uniflow/op/extract/load/html_op.py
Comparison with `unstructured`
- text context: Both `unstructured` and our `ExtractHTMLFlow` perform well.
- table content: Both `unstructured` and our `ExtractHTMLFlow` perform well.
- list content: Both `unstructured` and our `ExtractHTMLFlow` perform well.
- code block: Our `ExtractHTMLFlow` performs better.
- code in text: Both we and unstructured need to improve.
> Update rule-based html parser

- uniflow/op/extract/load/aws/s3_op.py
Previous implementation will cause a bug when the S3 object key contains multiple levels of folders. The previous code is unable to download them and will generate an empty string. For example, if `value_dict["key"]` is "test_client/test.txt", the download will fail and the text will be empty.
Previous Implementation:
```
filename = os.path.join(self.LOCAL_FILE_PATH, value_dict["key"])
logger.info("Downloading %s to %s", value_dict["key"], filename)
self._s3_client.download_file(
Bucket=value_dict["bucket"],
Key=value_dict["key"],
Filename=filename)
```
In this pull request, I have implemented a solution using `tempfile`, which can resolve this issue.
> fix: fix s3_op

- example/transform/google_model.ipynb
- uniflow/flow/config.py
- uniflow/flow/transform/__init__.py
- uniflow/flow/transform/transform_google_flow.py
- uniflow/op/model/lm/model_server.py
- uniflow/op/model/model_config.py
Add Google AI Studio model server.
> Add Google AI Studio model server.

- example/extract/extract_html.ipynb
- uniflow/op/extract/load/html_op.py
- uniflow/op/extract/split/recursive_character_splitter.py
1. Improve HTML parser: fix text tag(p, span etc) parser and remove the `\n` in the text tag
2. Improve recursive splitter separators: add `.` as a separator for long text
> Improve HTML parser and recursive splitter

- tests/op/extract/split/test_markdown_header_splitter.py
- tests/op/extract/split/test_pattern_splitter_op.py
- tests/op/extract/split/test_recursive_character_splitter.py
- tests/op/extract/split/test_splitter_factory.py
Add the following tests:
- test_markdown_header_splitter
- cannot pass custom headers, e.g. `<h1> xx </h1>`
- test_recursive_character_splitter
- test_pattern_splitter_op
- test_splitter_factory
> Add op/extract/split Unit Test

- .gitignore
- example/application/gmail_filter.ipynb
- uniflow/flow/config.py
- uniflow/flow/extract/__init__.py
- uniflow/flow/extract/gcp/workspace/extract_gmail_flow.py
- uniflow/flow/server.py
- uniflow/op/extract/load/gcp/workspace/gmail_op.py
Add google workspace email filter uniflow application.
> Add google workspace email filter uniflow application

- example/pipeline/pipeline_s3_txt.ipynb
- example/pipeline/pipeline_web_summary.ipynb
- example/toc.ipynb
- example/transform/google_multimodal_model.ipynb
- pyproject.toml
- uniflow/__init__.py
- Fix notebook
- Bump up version to 0.0.28
> Bump up version to 0.0.28

- uniflow/flow/server.py
- uniflow/op/model/model_config.py
Since [Google's model](https://github.com/CambioML/uniflow-llm-based-pdf-extraction-text-cleaning-data-clustering/blob/a58216cc85bd673b8a73c68ea9c82fcad45a4f5d/uniflow/op/model/model_config.py#L17), [OpenAI's model](https://github.com/CambioML/uniflow-llm-based-pdf-extraction-text-cleaning-data-clustering/blob/a58216cc85bd673b8a73c68ea9c82fcad45a4f5d/uniflow/op/model/model_config.py#L41), and [Azure OpenAI's model](https://github.com/CambioML/uniflow-llm-based-pdf-extraction-text-cleaning-data-clustering/blob/a58216cc85bd673b8a73c68ea9c82fcad45a4f5d/uniflow/op/model/model_config.py#L54) don't support batching locally, we will instead use `num_thread` to "fake batch" the data.
> Refinement: setting batch_size for different models

- tests/flow/extract/test_extract_html_flow.py
- tests/flow/extract/test_extract_image_flow.py
- tests/flow/extract/test_extract_ipynb_flow.py
- tests/flow/extract/test_extract_md_flow.py
- tests/flow/extract/test_extract_pdf_flow.py
- tests/flow/extract/test_extract_txt_flow.py
I have finished test_extract_txt_flow.py, let me know any I need modify.
> finish test_extract_txt_flow
